# Generated by Django 3.2.11 on 2022-03-05 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalempresa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalempresa',
            name='id_empleado',
        ),
        migrations.AlterField(
            model_name='personalempresa',
            name='id',
            field=models.IntegerField(blank=True, primary_key=True, serialize=False),
        ),
    ]
