# Generated by Django 3.2.11 on 2022-03-01 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_sidebar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sidebar',
            name='titulo',
        ),
    ]
