# Generated by Django 3.2.11 on 2022-03-04 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_footertext'),
    ]

    operations = [
        migrations.AddField(
            model_name='footertext',
            name='body',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
