# Generated by Django 3.2.11 on 2022-03-04 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_footertext_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footertext',
            name='body',
        ),
        migrations.RemoveField(
            model_name='footertext',
            name='url',
        ),
    ]
