# Generated by Django 3.2.11 on 2022-03-05 16:48

from django.db import migrations
import modelcluster.contrib.taggit


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('blog', '0019_auto_20220304_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viajespage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='blog.ViajePageTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
